### ISSUE TITLE
Leave a bit more information in profile

### ISSUE THREAD

**Issue by Vinteuil** [oforicedric/neugoj#22]
:information_source:

**Comment by oforicedric** [comment]
Was included in the feedback. Lets add basic analytics
1. total hours studied
1. how many points from the next rewards
2. weekly average 
3. Leaderboard

**Comment by Vinteuil** [comment]
Should be able to do this before YC except for the leaderboard, that will require a bit more thought

**Comment by Vinteuil** [comment]
average will probably have to go as well

**Comment by Vinteuil** [comment]
done but need to fix resulting problems with db
